### PR TITLE
Add a proper license

### PR DESCRIPTION
**Pull request by EraYaN**
Alright so I'd like to license this MPL-2.0.

Consent list:

- [x] @EraYaN
- [x] @dmitrylyzo
- [x] @TrueTechy 
- [x] @Narfinger
- [x] @JustAMan 
- [x] @dkanada 

Please respond with an affirmative for the license change in a comment. (Or edit this comment with the tick boxes)

### CODE REVIEW

**Comment by dkanada** [comment]
I'm not a fan of licenses that require headers, but other than that I'm okay with whatever we end up choosing in this pull request.

**Comment by JustAMan** [comment]
> All files that came form play-z will need the following notice:

Do we have those? What exact files are they?

Anyway, I think I'd like dual-license of MPL-2.0 + GPL3 (or AGPL3 for that matter).

**Comment by EraYaN** [comment]
This one: https://github.com/jellyfin/jellyfin-webos/blob/master/org.jellyfin.webos/js/ajax.js it already has the right header. But we can relicence our changes under the MPL. (not under the GPL I don't think) or just leave it Apache 2.0.

**Comment by JustAMan** [comment]
Let's go with MPL2 then IMHO

**Comment by dkanada** [comment]
sounds good

**Comment by dmitrylyzo** [comment]
:heavy_check_mark: _SIGNATURE goes here_

**Comment by TrueTechy** [comment]
Sounds good

**Comment by Narfinger** [comment]
I approve of this licence change to MPL2

**Pull request merged**
