### PR TITLE
Add DTS and TrueHD support detection

### PR DESCRIPTION
**Pull request by dmitrylyzo**
It looks like `tv.model.edidType` isn't supported by the webOS 1/3/5 emulator. So I can't really test this.

**Changes**
- Read the status of DTS support with a service request.
- Read the status of TrueHD support with a service request.

**Issues**
https://github.com/jellyfin/jellyfin-webos/issues/190#issuecomment-2054107367

### CODE REVIEW

**Comment by sundermann** [comment]
It looks good from a first glance. However, you have to remove the TrueHD part completely. TrueHD is not support on any TV for internal apps. `tv.model.edidType` is supposed to signal the capabilities of the eARC port. I think the TVs can passthrough TrueHD from an external HDMI source to a connected soundbar which is the intention behind this field. As I said earlier this detection only works properly for webOS 5 and later devices because on older webOS it was only possible to passthrough dts to a connected AVR or soundbar. dts via internal speakers is only possible on select webOS 23+ models. The webOS < 5 case was broken before anyway since the presence of dts support was just assumed based on the browser version so I guess the behaviour is still as it was before.

**Comment by dmitrylyzo** [comment]
> `tv.model.edidType` is supposed to signal the capabilities of the eARC port.

Does it depend on the device (soundbar) connected to it? Or if device is disconnected?

> dts via internal speakers (and external device) is only possible on select webOS 23+ models.

I believe DTS can be remuxed to stereo by TV itself if it supports (can decode) it.

**Comment by sundermann** [comment]
> Does it depend on the device (soundbar) connected to it? Or if device is disconnected?

AFAIK no, it only signals if the TV could technically support dts. Independent if a soundbar is connected or not.

> I believe DTS can be remuxed to stereo by TV itself if it supports (can decode) it.

Yes, but only on selected webOS 23+. On 4.x it was possible to passthrough dts to a connected soundbar but it was not possible to play via internal speakers.

**Comment by hmonteiro** [comment]
According to LG specs, this 4.x TV has a dts decoder: https://www.lg.com/uk/tvs-soundbars/nanocell/49sk8500pla/

**Comment by sundermann** [comment]
I wouldn't trust the specifications. Those often have errors. That said, this PR isn't going to change anything for webOS 4 and below as it will still always enable dts support as it was before.

**Comment by dmitrylyzo** [comment]
Since this method is unreliable, delegate the responsibility to the user.
Superseded by https://github.com/jellyfin/jellyfin-web/pull/5391

**Comment by hmonteiro** [comment]
I just tested a file with dts audio on the above mentioned model and it worked fine with direct play.

**Pull request closed without merging**
